# Generated by Django 4.1.10 on 2023-11-24 14:04

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('query', models.TextField()),
                ('contact_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_name', models.CharField(max_length=100)),
                ('prop_img', models.FileField(upload_to='properties')),
                ('prop_location', models.CharField(max_length=100)),
                ('prop_address', models.CharField(max_length=200)),
                ('prop_gmap', models.CharField(max_length=200)),
                ('prop_facilities', models.CharField(max_length=100)),
                ('prop_price', models.BigIntegerField()),
                ('prop_details', models.TextField()),
                ('prop_gender', models.CharField(max_length=50)),
                ('is_active', models.CharField(default='true', max_length=5)),
                ('prop_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='prop_name')),
                ('prop_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('is_Rated', models.BooleanField(default=False)),
                ('user_ip', models.GenericIPAddressField()),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.properties')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHolder',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_aadhaar', models.CharField(max_length=30)),
                ('owner_pan', models.CharField(max_length=10)),
                ('owner_city', models.CharField(max_length=50)),
                ('owner_state', models.CharField(max_length=50)),
                ('owner_pin', models.CharField(max_length=10)),
                ('owner_address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('enq_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('property', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('enquire_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.properties')),
            ],
        ),
    ]
