# Generated by Django 4.1.10 on 2023-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='prop_img',
            field=models.FileField(upload_to='properties'),
        ),
    ]
