# Generated by Django 4.1.10 on 2023-11-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0002_alter_properties_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.rating'),
        ),
    ]
