# Generated by Django 4.1.10 on 2023-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0002_alter_properties_prop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='prop_price',
            field=models.BigIntegerField(),
        ),
    ]
