# Generated by Django 4.1.10 on 2023-11-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0003_alter_properties_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='score',
        ),
    ]
